name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - name: Build succeed test
      run: cargo build --verbose -p strict_linking_success_test
    - name: Build fail test
      run: cargo run -p prove-it-fails -- cargo build --verbose -p strict_linking_fail_test
    - name: Run tests
      run: cargo test --verbose -p strict_linking
